import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { UserContextProvider } from "./context/userContext/UserContext";
import { PostContextProvider } from "./context/postContext/PostContext";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "DeepLime - Share Your Blog With Your Friends and Family",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/images/logo.png"
          type="image/x-icon"
        />
      </head>
      <body className={outfit.className}>
        <PostContextProvider>
          <UserContextProvider>
            <div className="container">
              <Header />
              {children}
              <Footer />
            </div>
          </UserContextProvider>
        </PostContextProvider>
      </body>
    </html>
  );
}
