import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { UserContextProvider } from "./context/userContext/UserContext";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "DailRose - Share Your Blog With Your Friends and Family",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <UserContextProvider>
          <div className="container">
            <Header />
            {children}
            {/* <Footer /> */}
          </div>
        </UserContextProvider>
      </body>
    </html>
  );
}
